//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessObjectLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class EvaluationResult
    {
        public int EvaluationResultId { get; set; }
        public int EvaluationManagementId { get; set; }
        public int QuestionId { get; set; }
        public string Answer { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public string IsDelete { get; set; }
    
        public virtual EvaluationManagement EvaluationManagement { get; set; }
        public virtual Question Question { get; set; }
    }
}
