//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessObjectLayer
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ORESEntities : DbContext
    {
        public ORESEntities()
            : base("name=ORESEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ActivityLog> ActivityLogs { get; set; }
        public virtual DbSet<AnswerType> AnswerTypes { get; set; }
        public virtual DbSet<Evaluation> Evaluations { get; set; }
        public virtual DbSet<EvaluationManagement> EvaluationManagements { get; set; }
        public virtual DbSet<EvaluationResult> EvaluationResults { get; set; }
        public virtual DbSet<Exception> Exceptions { get; set; }
        public virtual DbSet<Form> Forms { get; set; }
        public virtual DbSet<Group> Groups { get; set; }
        public virtual DbSet<GroupMember> GroupMembers { get; set; }
        public virtual DbSet<MailConfiguration> MailConfigurations { get; set; }
        public virtual DbSet<MailScheduling> MailSchedulings { get; set; }
        public virtual DbSet<Question> Questions { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<RolesRightsManagement> RolesRightsManagements { get; set; }
        public virtual DbSet<User> Users { get; set; }
    }
}
